### PR TITLE
Split maps.jinja

### PR DESCRIPTION
**Pull request by alxwr**
- into defaults, osfamilymap & osmap.
- Added Raspbian support.

Tested on `Raspbian GNU/Linux 9.6 (stretch)`.

### CODE REVIEW

**Comment by alxwr** [comment]
@aboe76 Ping? :-)

**Comment by aboe76** [comment]
@alxwr can you use the newer map.jinja style from ```template-formula```

**Comment by aboe76** [comment]
@alxwr by the way we created a master project in salt-formulas if you like to help:
https://github.com/orgs/saltstack-formulas/projects/1

**Comment by alxwr** [comment]
> @alxwr can you use the newer map.jinja style from `template-formula`

I would, if I was convinced it's compatible to `salt-ssh`. :-)
https://github.com/saltstack/salt/issues/51605

Let's merge this PR now and edit `map.jinja` when #51605 has been resolved.

> @alxwr by the way we created a master project in salt-formulas if you like to help:
> https://github.com/orgs/saltstack-formulas/projects/1

I'll have a look from time to time. (I won't promise things I can't keep.) Thanks for mentioning it!

**Comment by aboe76** [comment]
@alxwr ok perfect thanks

**Comment by myii** [comment]
@alxwr I agree that we have to wait until the upstream bug has been resolved, unfortunately.  In terms of a more general view of things, then https://github.com/saltstack-formulas/template-formula/issues/21 is bit easier to follow for now!

**Comment by alxwr** [comment]
@aboe76 Thanks for the merge!
@myii In the meantime we could use a `map.jinja` like in https://github.com/saltstack-formulas/openssh-formula/pull/151 ? (At least it works. :-) )

**Comment by myii** [comment]
@alxwr As always, PRs welcome!

**Comment by alxwr** [comment]
> @alxwr As always, PRs welcome!

Here you go: https://github.com/saltstack-formulas/template-formula/pull/25 :-)

**Pull request merged**
